version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - QingqiShi
  ignore:
  - dependency-name: react-spring
    versions:
    - "> 9.0.0.pre.canary.809.5.f01ecc2"
    - "< 9.1"
