pull_request_rules:
  - name: automatic merge on dependency bump and ci success
    conditions:
      - author=dependabot-preview[bot]
      - status-success=PR Checks / main (pull_request)
      - base=master
    actions:
      merge:
        method: merge
