pull_request_rules:
  - name: automatic merge on dependency bump and ci success
    conditions:
      - author=dependabot-preview[bot]
      - 'status-success=ci/circleci: lint'
      - 'status-success=ci/circleci: test'
      - 'status-success=ci/circleci: build'
      - base=master
    actions:
      merge:
        method: merge
