version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Unit tests
          command: npm test -- --coverage
      - codecov/upload:
          file: coverage/lcov.info
      - run:
          name: Build
          command: npm run build
      - run:
          name: Prepare deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm install --prefix=./firebase-deploy firebase-tools
            fi
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                ./firebase-deploy/node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
            fi
